org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.219
loader_version_range=[1,)

mod_id=createphantom
mod_name=Create Phantom
mod_license=BSD-3-Clause
mod_version=1.0.1
mod_group_id=com.yision.phantom
mod_authors=yision,gallium
mod_description=Add package delivery functionality to Phantom.

create_version=6.0.10-280
create_version_range=[6.0.10,)
ponder_version=1.0.82
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67
jei_version=19.21.0.247
fluidlogistics_version_range=[1.2.5,)
curios_version=9.5.1+1.21.1
curios_version_range=[9.5.1,)
sable_version=2.0.2
sable_version_range=[2.0.2,)
